sudo: required

dist: trusty

language: go

go:
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

addons:
  postgresql: 9.6
  apt:
    packages:
      - postgresql-9.6
      - postgresql-contrib-9.6

env:
  CI_SERVICE=travis-ci

before_install:
  - psql -U postgres -c "CREATE USER stryve WITH PASSWORD 'secret';"
  - psql -U postgres -c 'CREATE DATABASE stryve_test;'
  - psql -U postgres -c 'GRANT ALL PRIVILEGES ON DATABASE stryve_test TO stryve;'
  - psql -U postgres stryve_test -c 'CREATE EXTENSION "pgcrypto";'

install:
  - go get -v golang.org/x/tools/cmd/goimports
  - go get -v github.com/golang/lint/golint
  - go get -v github.com/gordonklaus/ineffassign
  - go get -v github.com/client9/misspell/cmd/misspell
  - go get -v github.com/nicklaw5/gosweep
  - go get -v github.com/mattn/goveralls
  - go get -v github.com/Masterminds/glide
  - glide install

script:
  - bash ${GOPATH}/src/github.com/nicklaw5/gosweep/gosweep.sh
